name: gift-meae


channels:
  - conda-forge
  - pytorch
  - defaults


dependencies:
  - python=3.8
  - git
  - pip

  # core scientific stack (conda)
  - numpy
  - scipy
  - pandas
  - scikit-learn
  - scikit-image
  - matplotlib
  - tqdm

  # Video and Image Processing
  - opencv

  # GUI
  - pyqt=5

  # pytorch
  - pytorch
  - torchvision

  # other dependencies
  - shapely
  - loguru
  

  - pip:
    - platformdirs
    - openmim
    - imutils
    - filterpy
    - dtw
    - lap
    - gdown
    - ftfy
    - regex